default_platform(:ios)

platform :ios do
# Lane Description
  desc "Create app on Apple Developer and App Store Connect sites"
# Names the lane
  lane :create_app do
# Adds app to developer portal and App Store connect
​    produce
  end

  desc "Take screenshots"
  lane :screenshot do
    snapshot
  end
end
